//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.17.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------

namespace lulz
{
    using Terminal.Gui;


    public partial class MyView
    {
        public MyView()
        {
            InitializeComponent();
            ApplyTurboVisionTheme();
        }

        private static void ShowHelp()
        {
            MessageBox.Query(
                60, 12,
                "Help — Log Commander",
                "  Log Commander v0.1\n\n" +
                "  F1   This help screen\n" +
                "  F3   Open a log file\n" +
                "  F10  Exit\n\n" +
                "  Use arrow keys to navigate the log table.\n" +
                "  Ctrl+Q also exits at any time.",
                "  OK  ");
        }

        private void ApplyTurboVisionTheme()
        {
            // Window interior: white on dark blue — classic TV window background
            var windowScheme = new ColorScheme
            {
                Normal    = Application.Driver.MakeAttribute(Color.White,        Color.Blue),
                HotNormal = Application.Driver.MakeAttribute(Color.BrightYellow, Color.Blue),
                Focus     = Application.Driver.MakeAttribute(Color.Black,        Color.Cyan),
                HotFocus  = Application.Driver.MakeAttribute(Color.Black,        Color.BrightCyan),
                Disabled  = Application.Driver.MakeAttribute(Color.Gray,         Color.Blue)
            };

            // Menu bar + status bar: black on bright white — ANSI 15 renders as actual light bar
            // (Color.Gray = ANSI 7 renders near-black on dark-theme terminals, so use White instead)
            var chromeScheme = new ColorScheme
            {
                Normal    = Application.Driver.MakeAttribute(Color.Black,        Color.White),
                HotNormal = Application.Driver.MakeAttribute(Color.Blue,         Color.White),
                Focus     = Application.Driver.MakeAttribute(Color.Black,        Color.Green),
                HotFocus  = Application.Driver.MakeAttribute(Color.BrightYellow, Color.Green),
                Disabled  = Application.Driver.MakeAttribute(Color.DarkGray,     Color.White)
            };

            // Table / list pane: white on blue, cyan highlight row
            var tableScheme = new ColorScheme
            {
                Normal    = Application.Driver.MakeAttribute(Color.White,        Color.Blue),
                HotNormal = Application.Driver.MakeAttribute(Color.BrightYellow, Color.Blue),
                Focus     = Application.Driver.MakeAttribute(Color.Black,        Color.Cyan),
                HotFocus  = Application.Driver.MakeAttribute(Color.Black,        Color.BrightCyan),
                Disabled  = Application.Driver.MakeAttribute(Color.Gray,         Color.Blue)
            };

            ColorScheme              = windowScheme;
            tableView.ColorScheme    = tableScheme;
            statusBar.ColorScheme    = chromeScheme;
            menuBar.ColorScheme      = chromeScheme;

            Border.BorderStyle     = BorderStyle.Double;
            Border.Effect3D        = false;
            Border.DrawMarginFrame = true;

            tableView.Style.AlwaysShowHeaders               = true;
            tableView.Style.ExpandLastColumn                = true;
            tableView.Style.InvertSelectedCellFirstCharacter = false;
            tableView.Style.ShowHorizontalHeaderOverline    = false;
            tableView.Style.ShowHorizontalHeaderUnderline   = true;
            tableView.Style.ShowVerticalCellLines           = false;
            tableView.Style.ShowVerticalHeaderLines         = false;

            // Re-wire status bar items with proper Borland-style F-key shortcuts and actions
            help    = new StatusItem(Key.F1,  "~F1~ Help",     ShowHelp);
            openLog = new StatusItem(Key.F3,  "~F3~ Open Log", null);
            quit    = new StatusItem(Key.F10, "~F10~ Quit",    () => Application.RequestStop());
            statusBar.Items = new[] { help, openLog, quit };
        }

        public override bool ProcessKey(KeyEvent keyEvent)
        {
            switch (keyEvent.Key)
            {
                case Key.F1:
                    ShowHelp();
                    return true;
                case Key.F10:
                case Key.CtrlMask | Key.Q:
                    Application.RequestStop();
                    return true;
            }

            return base.ProcessKey(keyEvent);
        }
    }
}
