
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.1.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace lulz {
    using System;
    using Terminal.Gui;
    
    
    public partial class MyView : Terminal.Gui.Window {
        
        private Terminal.Gui.TableView tableView;
        
        private Terminal.Gui.StatusBar statusBar;
        
        private Terminal.Gui.StatusItem help;
        
        private Terminal.Gui.StatusItem openLog;
        
        private Terminal.Gui.StatusItem quit;
        
        private Terminal.Gui.MenuBar menuBar;
        
        private Terminal.Gui.MenuBarItem fileF9Menu;
        
        private Terminal.Gui.MenuItem editMeMenuItem;
        
        private void InitializeComponent() {
            this.menuBar = new Terminal.Gui.MenuBar();
            this.statusBar = new Terminal.Gui.StatusBar();
            this.tableView = new Terminal.Gui.TableView();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Modal = false;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Double;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.Title = "Log Commander";
            this.tableView.Width = Dim.Fill(0);
            this.tableView.Height = Dim.Fill(1);
            this.tableView.X = 0;
            this.tableView.Y = 1;
            this.tableView.Visible = true;
            this.tableView.Data = "tableView";
            this.tableView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.tableView.FullRowSelect = true;
            this.tableView.Style.AlwaysShowHeaders = false;
            this.tableView.Style.ExpandLastColumn = true;
            this.tableView.Style.InvertSelectedCellFirstCharacter = false;
            this.tableView.Style.ShowHorizontalHeaderOverline = true;
            this.tableView.Style.ShowHorizontalHeaderUnderline = true;
            this.tableView.Style.ShowVerticalCellLines = true;
            this.tableView.Style.ShowVerticalHeaderLines = true;
            System.Data.DataTable tableViewTable;
            tableViewTable = new System.Data.DataTable();
            System.Data.DataColumn tableViewTableTimestamp;
            tableViewTableTimestamp = new System.Data.DataColumn();
            tableViewTableTimestamp.ColumnName = "Timestamp";
            tableViewTable.Columns.Add(tableViewTableTimestamp);
            System.Data.DataColumn tableViewTableLevel;
            tableViewTableLevel = new System.Data.DataColumn();
            tableViewTableLevel.ColumnName = "Level";
            tableViewTable.Columns.Add(tableViewTableLevel);
            System.Data.DataColumn tableViewTableShard;
            tableViewTableShard = new System.Data.DataColumn();
            tableViewTableShard.ColumnName = "Shard";
            tableViewTable.Columns.Add(tableViewTableShard);
            System.Data.DataColumn tableViewTableGroup;
            tableViewTableGroup = new System.Data.DataColumn();
            tableViewTableGroup.ColumnName = "Group";
            tableViewTable.Columns.Add(tableViewTableGroup);
            System.Data.DataColumn tableViewTableFacility;
            tableViewTableFacility = new System.Data.DataColumn();
            tableViewTableFacility.ColumnName = "Facility";
            tableViewTable.Columns.Add(tableViewTableFacility);
            System.Data.DataColumn tableViewTableMessage;
            tableViewTableMessage = new System.Data.DataColumn();
            tableViewTableMessage.ColumnName = "Message";
            tableViewTable.Columns.Add(tableViewTableMessage);
            this.tableView.Table = tableViewTable;
            this.Add(this.tableView);
            this.statusBar.Width = Dim.Fill(0);
            this.statusBar.Height = 1;
            this.statusBar.X = -1;
            this.statusBar.Y = Pos.AnchorEnd(1);
            this.statusBar.Visible = true;
            this.statusBar.Data = "statusBar";
            this.statusBar.Text = "1 Help";
            this.statusBar.TextAlignment = Terminal.Gui.TextAlignment.Right;
            this.help = new Terminal.Gui.StatusItem(((Terminal.Gui.Key)(1048588u)), "1 Help", null);
            this.openLog = new Terminal.Gui.StatusItem(((Terminal.Gui.Key)(1048590u)), "3 Open Log", null);
            this.quit = new Terminal.Gui.StatusItem(((Terminal.Gui.Key)(1048597u)), "10 Quit", null);
            this.statusBar.Items = new Terminal.Gui.StatusItem[] {
                    this.help,
                    this.openLog,
                    this.quit};
            this.Add(this.statusBar);
            this.menuBar.Width = Dim.Fill(0);
            this.menuBar.Height = 1;
            this.menuBar.X = 0;
            this.menuBar.Y = 0;
            this.menuBar.Visible = true;
            this.menuBar.Data = "menuBar";
            this.menuBar.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.fileF9Menu = new Terminal.Gui.MenuBarItem();
            this.fileF9Menu.Title = "_File (F9)";
            this.editMeMenuItem = new Terminal.Gui.MenuItem();
            this.editMeMenuItem.Title = "Edit Me";
            this.editMeMenuItem.Data = "editMeMenuItem";
            this.fileF9Menu.Children = new Terminal.Gui.MenuItem[] {
                    this.editMeMenuItem};
            this.menuBar.Menus = new Terminal.Gui.MenuBarItem[] {
                    this.fileF9Menu};
            this.Add(this.menuBar);
        }
    }
}
